# Generated by Django 4.2 on 2024-08-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_passwordresetmodel_delete_passwordreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password_reset_times",
            field=models.IntegerField(default=0),
        ),
    ]
