# Generated by Django 4.2 on 2024-08-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.IntegerField(
                choices=[
                    (37, 37),
                    (38, 38),
                    (39, 39),
                    (40, 40),
                    (41, 41),
                    (42, 42),
                    (43, 43),
                    (44, 44),
                    (45, 45),
                ]
            ),
        ),
    ]
