# Generated by Django 4.2 on 2024-08-17 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0005_remove_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="product",
            new_name="products",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together={("products", "user")},
        ),
    ]
