# Generated by Django 4.2 on 2024-08-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_rename_product_cart_products_product_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
