version: "3"

services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    container_name: "backend"
    command: python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000

  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    ports:
      - "3000:80"   
      - "25:25"   
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089

  # redis:
  #   image: redis:latest
  #   restart: always
  #   container_name: redis
  #   command: redis-server --save 60 1 --loglevel warning
  #   ports:
  #     - "6379:6379"

  # worker:
  #   build: .
  #   command: celery -A core worker --loglevel=warning
  #   restart: always
  #   depends_on:
  #     - redis
  #     - backend
