version: "3"

services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "7000:7000"
    container_name: "backend"
    command: python manage.py runserver 0.0.0.0:7000

  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    ports:
      - "3000:80"   # Web interface
      - "25:25"   # SMTP port
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
