version: "3"

services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "7000:8000"
    container_name: "backend"
    command: python manage.py runserver 0.0.0.0:7000
